.TH "LXPANEL" "1" 
.SH "NAME" 
lxpanelctl \(em controller for lxpanel. 
.SH "SYNOPSIS" 
.PP 
\fBlxpanelctl\fR command 
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBlxpanelctl\fR command. 
.PP 
\fBlxpanelctl\fR is a program that controls lxpanel. 
 
.SH "COMMANDS" 
.IP "\fBmenu\fR         " 10 
show system menu 
.IP "\fBrun\fR         " 10 
show run dialog 
.IP "\fBconfig\fR         " 10 
show config dialog 
.IP "\fBrestart\fR         " 10 
restart lxpanel 
.IP "\fBexit\fR         " 10 
exit lxpanel 
.SH "SEE ALSO" 
.PP 
lxpanel (1). 
.SH "AUTHOR" 
.PP 
This manual page was written by paulliu grandpaul@gmail.com for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Sat 31 May 2008, 03:35 
